[toolchain]

# Latest nightly for AVR support
channel = "nightly"

# Components for AVR development
components = [
    "rust-src",          # Required for core library customization
    "rustfmt",           # For code formatting
    "clippy",            # For additional linting
]

# Minimal profile since we're doing embedded development
profile = "minimal"