[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
# Baud Rates: 115200 57600 38400 19200 9600
runner = "ravedude uno -cb 57600 -P /dev/ttyACM0"

[unstable]
build-std = ["core"]
