[build]
target = "avr-unknown-gnu-atmega328"

[target.'cfg(target_arch = "avr")']
runner = "avrdude -c arduino -p atmega328p -P /dev/ttyACM0 -b 115200 -D -U flash:w:target/avr-unknown-gnu-atmega328/debug/rust-arduino-morse.elf"
