[build]
target = "avr-atmega328p"

[target.'cfg(target_arch = "avr")']
runner = "avrdude -c arduino -p atmega328p -P /dev/ttyACM0 -b 115200 -D -U flash:w:target/avr-atmega328p/debug/rust-arduino-morse.elf"
